// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unpmazefcnamhdwxdlzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVucG1hemVmY25hbWhkd3hkbHp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjUzNzUsImV4cCI6MjA2MjcwMTM3NX0.FpU8JfMqrIgcY-2y9WUnHAFb5e_f0vXeOlNEkkphpmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);